project_name: tools

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version=v{{.Version}}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: binary
    files:
      - none*

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^Merge'
      - '^test'
  groups:
    - title: 'Features'
      regexp: '^feat:'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^fix:'
      order: 1
    - title: 'Others'
      regexp: '^chore|^refactor|^style|^ci|^perf'
      order: 2

#https://goreleaser.com/customization/homebrew/?h=brews
brews:
  - tap:
      owner: 'xiaoxuan6'
      name: 'tools'
    homepage: 'https://godoc.org/github.com/xiaoxuan6/tools'
    description: 'tools - 小工具翻译、OCR 图片识别文字、二维码生成/解析等'
    test: |
      system "#{bin}/tools -h"
